name: inoue
on:
  pull_request:
    types: opened

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:
  inoue:
    name: Auto update Pull-request title to inoue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(github)
            github.rest.pulls.update({
              title:"井上"
            })
