name: inoue
on:
  pull_request:
    types: opened


jobs:
  inoue:
    name: Auto update Pull-request title to inoue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          script: |
            github.rest.pulls.update({
              title:"井上"
            })
